backend:
  name: git-gateway
  branch: main

media_folder: 'public/uploads'
public_folder: '/uploads'

collections:
  - name: 'framesData'
    label: 'FramesData'
    files:
      - label: 'AllFramesData'
        name: 'AllFramesData'
        file: 'src/content/FrameData.json'
        format: 'json'
        fields:
          - label: 'Frames'
            name: 'frames'
            widget: 'list'
            label_singular: 'Frame'
            fields:
              - label: 'ID'
                name: 'id'
                widget: 'number'
              - label: 'Type'
                name: 'type'
                widget: 'string'
              - label: 'Material'
                name: 'material'
                widget: 'string'
              - label: 'Weight'
                name: 'weight'
                widget: 'number'
              - label: 'Description'
                name: 'description'
                widget: 'text'
              - label: 'Image'
                name: 'image'
                widget: 'image'
              - label: 'Dimension Price'
                name: 'dimensionPrice'
                widget: 'list'
                fields:
                  - label: 'Size'
                    name: 'size'
                    widget: 'string'
                  - label: 'Price'
                    name: 'price'
                    widget: 'number'
                  - label: 'Preview'
                    name: 'preview'
                    widget: 'list'
                    fields:
                      - label: 'ID'
                        name: 'id'
                        widget: 'number'
                      - label: 'Image'
                        name: 'image'
                        widget: 'image'

  - name: 'ToysData'
    label: 'ToysData'
    files: 
      - label: 'AllToysData'
        name: 'AllToysData'
        file: 'src/content/ToysData.json'
        format: 'json'
        fields:
          - label: 'Toys'
            name: 'toys'
            widget: 'list'
            label_singular: 'Toy'
            fields:
              - label: 'ID'
                name: 'id'
                widget: 'number'
              - label: 'Name'
                name: 'name'
                widget: 'string'
              - label: 'Description'
                name: 'description'
                widget: 'text'
              - label: 'Price'
                name: 'price'
                widget: 'number'
              - label: 'Type'
                name: 'type'
                widget: 'string'
              - label: 'Scale'
                name: 'scale'
                widget: 'string'
              - label: 'Image'
                name: 'image'
                widget: 'image'

  - name: 'TestimonialsData'
    label: 'TestimonialsData'
    files:
      - label: 'AllTestimonialsData'
        name: 'AllTestimonialsData'
        file: 'src/content/TestimonialsData.json'
        format: 'json'
        fields:
          - label: 'Testimonials'
            name: 'testimonials'
            widget: 'list'
            label_singular: 'Testimonial'
            fields:
              - label: 'Username'
                name: 'username'
                widget: 'string'
              - label: 'Stars'
                name: 'stars'
                widget: 'number'
              - label: 'Testimonial'
                name: 'testimonial'
                widget: 'text'
  - name: 'GalleryData'
    label: 'GalleryData'
    files:
      - label: 'AllGalleryData'
        name: 'AllGalleryData'
        file: 'src/content/GalleryData.json'
        format: 'json'
        fields:
          - label: 'Gallery'
            name: 'gallery'
            widget: 'list'
            label_singular: 'Image'
            fields:
              - label: 'ID'
                name: 'id'
                widget: 'number'
              - label: 'ALT'
                name: 'alt'
                widget: 'string'
              - label: 'Caption'
                name: 'caption'
                widget: 'string'
              - label: 'Image'
                name: 'image'
                widget: 'image'
